"""create initial schema"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '8afbb8a8d088'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_versions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('build_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('config_version', sa.Text(), nullable=False),
    sa.Column('config_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', 'build_version', name='uq_course_versions_code_version_build_version')
    )
    op.create_table('kanji',
    sa.Column('char', sa.Text(), nullable=False),
    sa.Column('primary_meaning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('char')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('has_pro_sub', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patterns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('intro_order', sa.Integer(), nullable=False),
    sa.Column('is_bootstrap', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_version_id', 'code', name='uq_patterns_course_code'),
    sa.UniqueConstraint('course_version_id', 'intro_order', name='uq_patterns_course_intro_order')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('generation_description', sa.Text(), nullable=False),
    sa.Column('target_unit_count', sa.Integer(), nullable=False),
    sa.Column('target_new_word_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_version_id', 'code', name='uq_sections_course_code'),
    sa.UniqueConstraint('course_version_id', 'order_index', name='uq_sections_course_order_index')
    )
    op.create_table('theme_tags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_version_id', 'code', name='uq_theme_tags_course_code')
    )
    op.create_table('user_course_enrollments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_version_id', name='uq_user_course_enrollment')
    )
    op.create_table('words',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('intro_order', sa.Integer(), nullable=False),
    sa.Column('canonical_writing_ja', sa.Text(), nullable=False),
    sa.Column('reading_kana', sa.Text(), nullable=False),
    sa.Column('gloss_primary_en', sa.Text(), nullable=False),
    sa.Column('gloss_alternatives_en', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('usage_note_en', sa.Text(), nullable=True),
    sa.Column('pos', sa.Text(), nullable=False),
    sa.Column('is_safe_pool', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_bootstrap_seed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_kind', sa.Text(), server_default='llm', nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_version_id', 'canonical_writing_ja', 'reading_kana', name='uq_words_course_canonical_writing_reading'),
    sa.UniqueConstraint('course_version_id', 'intro_order', name='uq_words_course_intro_order')
    )
    op.create_table('planned_units',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('primary_theme_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pattern_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'order_index', name='uq_planned_units_section_order')
    )
    op.create_table('section_pattern_links',
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pattern_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', 'pattern_id')
    )
    op.create_table('section_theme_links',
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('theme_tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_tag_id'], ['theme_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', 'theme_tag_id')
    )
    op.create_table('section_words',
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', 'word_id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ja_text', sa.Text(), nullable=False),
    sa.Column('en_text', sa.Text(), nullable=False),
    sa.Column('target_word_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_pattern_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_pattern_id'], ['patterns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_word_id'], ['words.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_version_id', 'ja_text', 'en_text', 'target_word_id', 'target_pattern_id', name='uq_sentences_course_text_target')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('section_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'order_index', name='uq_units_section_order_index')
    )
    op.create_table('user_kanji_learned',
    sa.Column('enrollment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kanji_char', sa.Text(), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['user_course_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kanji_char'], ['kanji.char'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id', 'kanji_char')
    )
    op.create_table('user_pattern_learned',
    sa.Column('enrollment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pattern_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['user_course_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id', 'pattern_id')
    )
    op.create_table('user_words_learned',
    sa.Column('enrollment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('learned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['user_course_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id', 'word_id')
    )
    op.create_table('word_kanji_links',
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kanji_char', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kanji_char'], ['kanji.char'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id', 'kanji_char', 'order_index')
    )
    op.create_table('word_theme_links',
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('theme_tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['theme_tag_id'], ['theme_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id', 'theme_tag_id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('unit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('force_kana_display', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('target_item_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'order_index', name='uq_lessons_unit_order_index')
    )
    op.create_table('planned_lessons',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('planned_unit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('force_kana_display', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('target_item_count', sa.Integer(), nullable=False),
    sa.Column('introduced_word_lemmas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kanji_focus_word_lemmas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_word_lemmas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_pattern_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_pattern_code', sa.Text(), nullable=True),
    sa.Column('target_pattern_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available_word_lemmas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available_pattern_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_pattern_sentence_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planned_unit_id'], ['planned_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planned_unit_id', 'order_index', name='uq_planned_lessons_unit_order')
    )
    op.create_table('sentence_pattern_links',
    sa.Column('sentence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pattern_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sentence_id', 'pattern_id')
    )
    op.create_table('sentence_tile_sets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sentence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('answer_lang', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentence_id', 'answer_lang', name='uq_sentence_tile_sets_variant')
    )
    op.create_table('sentence_unit_hints',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sentence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('hint_text', sa.Text(), nullable=False),
    sa.Column('hint_kind', sa.Text(), nullable=False),
    sa.Column('is_new', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentence_units',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sentence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('surface', sa.Text(), nullable=False),
    sa.Column('lemma', sa.Text(), nullable=True),
    sa.Column('reading', sa.Text(), nullable=True),
    sa.Column('pos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentence_id', 'lang', 'unit_index', name='uq_sentence_units_index')
    )
    op.create_table('sentence_word_links',
    sa.Column('sentence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sentence_id', 'word_id')
    )
    op.create_table('unit_pattern_links',
    sa.Column('unit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pattern_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id', 'pattern_id')
    )
    op.create_table('unit_theme_links',
    sa.Column('unit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('theme_tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['theme_tag_id'], ['theme_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id', 'theme_tag_id')
    )
    op.create_table('unit_words',
    sa.Column('unit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id', 'word_id')
    )
    op.create_table('exam_attempts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('enrollment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['user_course_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('prompt_lang', sa.Text(), nullable=False),
    sa.Column('answer_lang', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'order_index', name='uq_items_lesson_order_index')
    )
    op.create_table('kanji_introductions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('course_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kanji_char', sa.Text(), nullable=False),
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('example_word_ja', sa.Text(), nullable=False),
    sa.Column('example_reading', sa.Text(), nullable=True),
    sa.Column('meaning_en', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kanji_char'], ['kanji.char'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_version_id', 'lesson_id', 'kanji_char', 'example_word_ja', name='uq_kanji_introductions_unique_usage')
    )
    op.create_table('lesson_pattern_links',
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pattern_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'pattern_id')
    )
    op.create_table('lesson_sentences',
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sentence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), server_default='core', nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'sentence_id')
    )
    op.create_table('lesson_words',
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'word_id')
    )
    op.create_table('sentence_tiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tile_set_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tile_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('unit_start', sa.Integer(), nullable=True),
    sa.Column('unit_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tile_set_id'], ['sentence_tile_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tile_set_id', 'tile_index', name='uq_sentence_tiles_order')
    )
    op.create_table('user_lesson_progress',
    sa.Column('enrollment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('lesson_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['user_course_enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id', 'lesson_id')
    )
    op.create_table('item_kanji_kana_match',
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prompt_script', sa.Text(), nullable=False),
    sa.Column('answer_script', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('item_sentence_tiles',
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sentence_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tile_set_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tile_set_id'], ['sentence_tile_sets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('item_word_choice',
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('word_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_word_choice')
    op.drop_table('item_sentence_tiles')
    op.drop_table('item_kanji_kana_match')
    op.drop_table('user_lesson_progress')
    op.drop_table('sentence_tiles')
    op.drop_table('lesson_words')
    op.drop_table('lesson_sentences')
    op.drop_table('lesson_pattern_links')
    op.drop_table('kanji_introductions')
    op.drop_table('items')
    op.drop_table('exam_attempts')
    op.drop_table('unit_words')
    op.drop_table('unit_theme_links')
    op.drop_table('unit_pattern_links')
    op.drop_table('sentence_word_links')
    op.drop_table('sentence_units')
    op.drop_table('sentence_unit_hints')
    op.drop_table('sentence_tile_sets')
    op.drop_table('sentence_pattern_links')
    op.drop_table('planned_lessons')
    op.drop_table('lessons')
    op.drop_table('word_theme_links')
    op.drop_table('word_kanji_links')
    op.drop_table('user_words_learned')
    op.drop_table('user_pattern_learned')
    op.drop_table('user_kanji_learned')
    op.drop_table('units')
    op.drop_table('sentences')
    op.drop_table('section_words')
    op.drop_table('section_theme_links')
    op.drop_table('section_pattern_links')
    op.drop_table('planned_units')
    op.drop_table('words')
    op.drop_table('user_course_enrollments')
    op.drop_table('theme_tags')
    op.drop_table('sections')
    op.drop_table('patterns')
    op.drop_table('users')
    op.drop_table('kanji')
    op.drop_table('course_versions')
    # ### end Alembic commands ###
