themes:
  primary:
    - code: "HOME_AND_ROOMS"
      name: "Home and rooms"
    - code: "TIME_SCHEDULE_AND_NUMBERS"
      name: "Time, schedule, and numbers"
    - code: "DESCRIPTION"
      name: "Description"
  secondary:
    - code: "FAMILY_AND_PEOPLE"
      name: "Family and people"
    - code: "NEARBY_PLACES"
      name: "Nearby places"
