themes:
  primary:
    - code: "SELF_AND_PEOPLE"
      name: "Self and people"
    - code: "REFERENCE_AND_QUESTIONS"
      name: "Reference and questions"
    - code: "FAMILY_AND_PERSONAL_INFO"
      name: "Family and personal information"
  secondary:
    - code: "EVERYDAY_THINGS"
      name: "Everyday things"
    - code: "PLACES_AND_LOCATIONS"
      name: "Places and locations"